# Generated by Django 5.1 on 2024-09-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('escolaridad', models.CharField(choices=[('', 'Seleccione un nivel escolar'), ('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto')], default='', max_length=40)),
                ('genero', models.CharField(choices=[('', 'Seleccione un género'), ('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
