# Generated by Django 5.0.6 on 2024-09-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_gendet_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nombre_acudiente',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='numero_de_identificacion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono_acudiente',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='escolaridad',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
