# Generated by Django 5.0.6 on 2024-09-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_info_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_info',
            name='nombre_acudiente',
            field=models.TextField(max_length=50, null=True, verbose_name='Nombre del acudiente'),
        ),
        migrations.AddField(
            model_name='perfil_info',
            name='telefono_acudiente',
            field=models.TextField(max_length=20, null=True, verbose_name='Teléfono del acudiente'),
        ),
    ]
