# Generated by Django 5.0.6 on 2025-02-12 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_perfil_info_nombre_acudiente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_info',
            name='email',
        ),
    ]
