# Generated by Django 5.1 on 2024-08-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulacion_como_pronunciar_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100, verbose_name='nombre')),
                ('instruciones', models.TextField(max_length=1000, verbose_name='instrucciones_actividad')),
                ('video', models.FileField(upload_to='videos/', verbose_name='video')),
                ('foto_mayuscula', models.ImageField(upload_to='fotos/', verbose_name='foto_mayuscula')),
                ('foto_minuscula', models.ImageField(upload_to='fotos/', verbose_name='foto_minuscula')),
            ],
        ),
        migrations.CreateModel(
            name='Articulacion_completar_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100, verbose_name='nombre')),
                ('imagen', models.ImageField(upload_to='fotos/', verbose_name='imagen')),
                ('texto_incompleto', models.TextField(max_length=30, verbose_name='texto_incompleto')),
                ('texto_completo', models.TextField(max_length=30, verbose_name='texto_completo')),
            ],
        ),
        migrations.CreateModel(
            name='Articulacion_seleccion_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100, verbose_name='nombre')),
                ('audio_a', models.FileField(upload_to='audios/', verbose_name='audio_a')),
                ('audio_e', models.FileField(upload_to='audios/', verbose_name='audio_e')),
                ('audio_i', models.FileField(upload_to='audios/', verbose_name='audio_i')),
                ('audio_o', models.FileField(upload_to='audios/', verbose_name='audio_o')),
                ('audio_u', models.FileField(upload_to='audios/', verbose_name='audio_u')),
            ],
        ),
    ]
