# Generated by Django 5.1 on 2024-08-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulacion_completar_info',
            name='nombre',
        ),
        migrations.AddField(
            model_name='articulacion_completar_info',
            name='letra_categoria',
            field=models.TextField(max_length=100, null=True, verbose_name='letra'),
        ),
    ]
