# Generated by Django 5.1 on 2024-08-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0003_rename_nombre_articulacion_seleccion_info_letra_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulacion_seleccion_info',
            name='letra_categoria',
            field=models.TextField(max_length=100, verbose_name='letra_categoria'),
        ),
    ]
