# Generated by Django 5.1 on 2024-08-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respiracion_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100, verbose_name='nombre')),
                ('instrucciones', models.TextField(max_length=1000, verbose_name='instrucciones_actividad')),
                ('video', models.FileField(upload_to='videos/', verbose_name='video')),
            ],
        ),
    ]
