# Generated by Django 5.1 on 2024-08-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discriminacion_auditiva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discriminacion_auditiva_escoger_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100, verbose_name='nombre')),
                ('imagen_correcta', models.ImageField(upload_to='fotos/', verbose_name='imagen_correcta')),
                ('imagen_incorrecta', models.ImageField(upload_to='fotos/', verbose_name='imagen_incorrecta')),
                ('audio', models.FileField(upload_to='audios/', verbose_name='audio')),
            ],
        ),
        migrations.RenameModel(
            old_name='Discriminacion_auditiva_info',
            new_name='Discriminacion_auditiva_seleccionar_info',
        ),
    ]
