# Generated by Django 5.1 on 2024-10-03 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discriminacion_auditiva', '0003_respuesta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
